spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8180/realms/ecom-realm/protocol/openid-connect/certs
      client:
        registration:
          ecom-service:
            provider: keycloak
            client-id: ecom-service
            client-secret: ecom-secret
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://keycloak:8180/realms/ecom-realm/protocol/openid-connect/token

product-service:
  url: ${PRODUCT_SERVICE_URL}

customer-service:
  url: ${CUSTOMER_SERVICE_URL}

fraud-detection-service:
  url: ${FRAUD_DETECTION_SERVICE_URL}
